config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'hl7#home'

  get 'hl7_lookup' => 'hl7#hl7_lookup'
  get 'hl7_parser' => 'hl7#hl7_parser'
  get 'adt_events' => 'hl7#adt_events'
  post 'parse_hl7' => 'hl7#parse_hl7'
end

app/models/hl7.rb
class Hl7# < ApplicationRecord
    attr_reader :message, :segments

    def initialize(args={})
        @message = args[:message]
        @segments = Segments.new(@message)
    end

    def errors
        error_list = []
        if !in_segments?('MSH')
            error_list << 'Missing MSH segment'
        end

        if !in_segments?('PID')
            error_list << 'Missing PID segment'
        end

        return error_list
    end

    def type
        #todo
    end

    def self.adt_event_dict
        {
            A01: "Admit/visit notification",
            A02: "Transfer a patient",
            A03: "Discharge/end visit",
            A04: "Register a patient",
            A05: "Pre-admit a patient",
            A06: "Change an outpatient to an inpatient",
            A07: "Change an inpatient to an outpatient",
            A08: "Update patient information",
            A09: "Patient departing - tracking",
            A10: "Patient arriving - tracking",
            A11: "Cancel admit/visit notification",
            A12: "Cancel transfer",
            A13: "Cancel discharge/end visit",
            A14: "Pending admit",
            A15: "Pending transfer",
            A16: "Pending discharge",
            A17: "Swap patients",
            A18: "Merge patient information",
            A19: "Patient query",
            A20: "Bed status update",
            A21: "Patient goes on a leave of absence",
            A22: "Patient returns from a leave of absence",
            A23: "Delete a patient record",
            A24: "Link patient information",
            A25: "Cancel pending discharge",
            A26: "Cancel pending transfer",
            A27: "Cancel pending admit",
            A28: "Add person information",
            A29: "Delete person information",
            A30: "Merge person information",
            A31: "Update person information",
            A32: "Cancel patient arriving - tracking",
            A33: "Cancel patient departing - tracking",
            A34: "Merge patient information - patient ID only",
            A35: "Merge patient information - account number only",
            A36: "Merge patient information - patient ID and account number",
            A37: "Unlink patient information",
            A38: "Cancel pre-admit",
            A39: "Merge person - patient ID",
            A40: "Merge patient - patient identifier list",
            A41: "Merge account - patient account number",
            A42: "Merge visit - visit number",
            A43: "Move patient information - patient identifier list",
            A44: "Move account information - patient account number",
            A45: "Move visit information - visit number",
            A46: "Change patient ID",
            A47: "Change patient identifier list",
            A48: "Change alternate patient ID",
            A49: "Change patient account number",
            A50: "Change visit number",
            A51: "Change alternate visit ID",
            A52: "Cancel leave of absence for a patient",
            A53: "Cancel patient returns from a leave of absence",
            A54: "Change attending doctor",
            A55: "Cancel change attending doctor",
            A60: "Update allergy information",
            A61: "Change consulting doctor",
            A62: "Cancel change consulting doctor"
        }
    end

    def self.field_dict
             {
                ABS1: "Discharge Care Provider",
                ABS2: "Transfer Medical Service Code",
                ABS3: "Severity of Illness Code",
                ABS4: "Date/Time of Attestation",
                ABS5: "Attested By",
                ABS6: "Triage Code",
                ABS7: "Abstract Completion Date/Time",
                ABS8: "Abstracted By",
                ABS9: "Case Category Code",
                ABS10: "Caesarian Section Indicator",
                ABS11: "Gestation Category Code",
                ABS12: "Gestation Period - Weeks",
                ABS13: "Newborn Code",
                ABS14: "Stillborn Indicator",
                ACC1: "Accident Date/Time",
                ACC2: "Accident Code",
                ACC3: "Accident Location",
                ACC4: "Auto Accident State",
                ACC5: "Accident Job Related Indicator",
                ACC6: "Accident Death Indicator",
                ACC7: "Entered By",
                ACC8: "Accident Description",
                ACC9: "Brought In By",
                ACC10: "Police Notified Indicator",
                ACC11: "Accident Address",
                ACC12: "Degree of patient liability",
                ACC13: "Accident Identifier",
                ADD1: "Addendum Continuation Pointer",
                ADJ1: "Provider Adjustment Number",
                ADJ2: "Payer Adjustment Number",
                ADJ3: "Adjustment Sequence Number",
                ADJ4: "Adjustment Category",
                ADJ5: "Adjustment Amount",
                ADJ6: "Adjustment Quantity",
                ADJ7: "Adjustment Reason PA",
                ADJ8: "Adjustment Description",
                ADJ9: "Original Value",
                ADJ10: "Substitute Value",
                ADJ11: "Adjustment Action",
                ADJ12: "Provider Adjustment Number Cross Reference",
                ADJ13: "Provider Product/Service Line Item Number Cross Reference",
                ADJ14: "Adjustment Date",
                ADJ15: "Responsible Organization",
                AFF1: "Set ID - AFF",
                AFF2: "Professional Organization",
                AFF3: "Professional Organization Address",
                AFF4: "Professional Organization Affiliation Date Range",
                AFF5: "Professional Affiliation Additional Information",
                AIG1: "Set ID - AIG",
                AIG2: "Segment Action Code",
                AIG3: "Resource ID",
                AIG4: "Resource Type",
                AIG5: "Resource Group",
                AIG6: "Resource Quantity",
                AIG7: "Resource Quantity Units",
                AIG8: "Start Date/Time",
                AIG9: "Start Date/Time Offset",
                AIG10: "Start Date/Time Offset Units",
                AIG11: "Duration",
                AIG12: "Duration Units",
                AIG13: "Allow Substitution Code",
                AIG14: "Filler Status Code",
                AIL1: "Set ID - AIL",
                AIL2: "Segment Action Code",
                AIL3: "Location Resource ID",
                AIL4: "Location Type - AIL",
                AIL5: "Location Group",
                AIL6: "Start Date/Time",
                AIL7: "Start Date/Time Offset",
                AIL8: "Start Date/Time Offset Units",
                AIL9: "Duration",
                AIL10: "Duration Units",
                AIL11: "Allow Substitution Code",
                AIL12: "Filler Status Code",
                AIP1: "Set ID - AIP",
                AIP2: "Segment Action Code",
                AIP3: "Personnel Resource ID",
                AIP4: "Resource Type",
                AIP5: "Resource Group",
                AIP6: "Start Date/Time",
                AIP7: "Start Date/Time Offset",
                AIP8: "Start Date/Time Offset Units",
                AIP9: "Duration",
                AIP10: "Duration Units",
                AIP11: "Allow Substitution Code",
                AIP12: "Filler Status Code",
                AIS1: "Set ID - AIS",
                AIS2: "Segment Action Code",
                AIS3: "Universal Service Identifier",
                AIS4: "Start Date/Time",
                AIS5: "Start Date/Time Offset",
                AIS6: "Start Date/Time Offset Units",
                AIS7: "Duration",
                AIS8: "Duration Units",
                AIS9: "Allow Substitution Code",
                AIS10: "Filler Status Code",
                AIS11: "Placer Supplemental Service Information",
                AIS12: "Filler Supplemental Service Information",
                AL11: "Set ID - AL1",
                AL12: "Allergen Type Code",
                AL13: "Allergen Code/Mnemonic/Description",
                AL14: "Allergy Severity Code",
                AL15: "Allergy Reaction Code",
                AL16: "Identification Date",
                APR1: "Time Selection Criteria",
                APR2: "Resource Selection Criteria",
                APR3: "Location Selection Criteria",
                APR4: "Slot Spacing Criteria",
                APR5: "Filler Override Criteria",
                ARQ1: "Placer Appointment ID",
                ARQ2: "Filler Appointment ID",
                ARQ3: "Occurrence Number",
                ARQ4: "Placer Group Number",
                ARQ5: "Schedule ID",
                ARQ6: "Request Event Reason",
                ARQ7: "Appointment Reason",
                ARQ8: "Appointment Type",
                ARQ9: "Appointment Duration",
                ARQ10: "Appointment Duration Units",
                ARQ11: "Requested Start Date/Time Range",
                ARQ12: "Priority-ARQ",
                ARQ13: "Repeating Interval",
                ARQ14: "Repeating Interval Duration",
                ARQ15: "Placer Contact Person",
                ARQ16: "Placer Contact Phone Number",
                ARQ17: "Placer Contact Address",
                ARQ18: "Placer Contact Location",
                ARQ19: "Entered By Person",
                ARQ20: "Entered By Phone Number",
                ARQ21: "Entered By Location",
                ARQ22: "Parent Placer Appointment ID",
                ARQ23: "Parent Filler Appointment ID",
                ARQ24: "Placer Order Number",
                ARQ25: "Filler Order Number",
                ARV1: "Set ID",
                ARV2: "Access Restriction Action Code",
                ARV3: "Access Restriction Value",
                ARV4: "Access Restriction Reason",
                ARV5: "Special Access Restriction Instructions",

app/controllers/hl7_controller.rb
class Hl7Controller < ApplicationController

  def parse_hl7
    @hl7 = Hl7.new(message: parser_params[:message])

    respond_to do |format|
      format.js
    end
  end

  def hl7_parser
  end

  def hl7_lookup
    @dict = Hl7.field_dict.group_by{|k, v| k[0..2]}
  end

  def home
  end

  def adt_events
    @events = Hl7.adt_event_dict
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def parser_params
      params.permit(:message)
    end
end

app/helpers/hl7_helper.rb
module Hl7Helper
end

app/views/hl7/_hl7_parser.html.haml
%h4 Load Sample Message

#sample-messages
    %select.custom-select(id="message-select")
        %option(selected disabled) Sample Messages...
        %option(value="#{sample_adt_a01}") ADT
        %option(value="#{sample_discrete_lab}") Lab
        %option(value="#{sample_pharmacy}") Pharmacy
        %option(value="#{sample_errors}") Message with Errors

=form_tag("/parse_hl7", method: 'post', remote: true) do
    = text_area_tag 'message', '', class: "form-control auto-expand" , rows: 1, autocomplete: "off", placeholder: "Input an HL7 message!"
    = submit_tag 'Parse!', class: "btn btn-primary w-100"

app/views/hl7/_interactive_seg.html.haml
- if segment.errors.size > 0
    .row.seg-error
        .col
            - segment.errors.each do |e|
                %span.bg-danger.text-light.rounded.seg-error #{e}

.row.interactive-seg.mt-2{id: "seg-#{index}"}
    .col
        - segment.fields.each_with_index do |f|
            %span{ class: ("empty-field" if f.value.empty?) }(class="interactive-field" data-toggle="tooltip" data-placement="top" title="#{field_tooltip(f)}")><=f.value
            |
    .col-lg-2.col-md-auto
        %button{class: "crosswalk-toggle btn btn-primary btn-sm float-right"} Toggle Table
.row.seg-crosswalk.mt-2{id: "crosswalk-#{index}", style: "display:none"}
    .col
        %table{class: "seg-table table table-striped table-sm"}
            %tr
                %th Segment-Field
                %th Field Description
                %th Value
            - segment.fields.each do |f|
                -if f.index != 0
                    %tr
                        %td #{f.seg_type}-#{f.index}
                        %td #{f.description}
                        %td #{f.value}
%hr.seg-hr

app/views/hl7/_parser_error.html.haml
.row.parser-error
    .col
        %span #{error}

app/views/hl7/adt_events.html.haml
- title "HL7 ADT Event Codes"

%h1.mt-3 HL7 ADT Event Codes
.open-sans.pt-2.pb-2
    These ADT event codes are up to date with HL7 2.8.2 standards. The event code should be sent in MSH-9.2 and EVN-1 (if EVN segment is sent).
.row
    .col
        %table{class: "seg-table table table-striped table-sm"}
            %tr
                %th Event Code
                %th Event Description
            - @events.each do |event, desc|
                %tr
                    %td #{event.to_s}
                    %td.open-sans #{desc}

app/views/hl7/hl7_lookup.html.haml
- title "HL7 Lookup/Crosswalk Table"

.sticky-top#lookup-nav.bg-white
    %select.custom-select
        %option(selected disabled) Jump to...
        - @dict.each do |seg|
            %option(value="#{seg[0]}") #{seg[0]}

.row
    .col
        %h1.mt-3 HL7 Lookup/Crosswalk Table
        .open-sans.pt-2.pb-2
            Looking to search by description? Use Ctrl+F to search with your browser.
        - @dict.each do |seg|
            .row
                .col
                    %h3{id: seg[0]} #{seg[0]}
                    %table{class: "seg-table table table-striped table-sm"}
                        %tr
                            %th Field
                            %th Field Description
                        - seg[1].each do |f|
                            %tr
                                %td #{f[0].to_s.insert(3, "-")}
                                %td.open-sans #{f[1]}

app/views/hl7/hl7_parser.html.haml
- title "Free Interactive HL7 Parser"

.row
    .col
        %h1.mt-3 Free Interactive HL7 Parser

        #hl7-parser-info.open-sans
            %p
                This HL7 parser utilizes HL7 2.8.1 definitions which are backwards compatible with all HL7 2.X versions.
                After parsing a message you can easily navigate the message by hovering over a field or expanding the definition table.
            %p
                No parsed data is saved/mined/etc. Intended for use with test data only while running externally.
            %p
                Paste in a message below or choose from a sample message to parse.

.row
    .col
        #parser-input.mt-3
            = render 'hl7_parser'

.row
    .col
        #parser-errors.bg-warning.rounded.d-none
        #parser-interactive.mt-3

app/views/hl7/home.html.haml
- title "Data Tools for Healthcare Professionals"

#home-cover.row.justify-content-center.align-items-center.text-center
    .col-12
        %h1#cover-heading.mt-5 Data Tools for Healthcare Professionals

        %p.lead.mt-3.text-muted
            Making life easier, one tool at a time.

    .col-12.pt-3
        = link_to "HL7 Parser", hl7_parser_path, :class => "btn btn-lg btn-outline-info"
    .col-12.pt-3
        = link_to "HL7 Lookup", hl7_lookup_path, :class => "btn btn-lg btn-outline-info"
    .col-12.pt-3
        = link_to "ADT Event Codes", adt_events_path, :class => "btn btn-lg btn-outline-info"

app/views/hl7/parse_hl7.js.haml
$('#parser-errors').html("")
- if @hl7.errors.size > 0
    $('#parser-errors').removeClass("d-none")
    $('#parser-errors').append("<strong>We found the following potential errors in this HL7 message:</strong>")
    - @hl7.errors.each_with_index do |e, i|
        $('#parser-errors').append("#{j render(partial: 'parser_error', locals: {error: e, index: i})}")
- else
    $('#parser-errors').addClass("d-none")

$('#parser-interactive').html("")
- @hl7.segments.each_with_index do |seg, i|
    $('#parser-interactive').append("#{j render(partial: 'interactive_seg', locals: {segment: seg, index: i})}")